twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      config: '@App\Model\AppConfig'
      base_url: '%base_url%'
      app_version: '%app_version%'
      documentation_link: '%documentation_link%'
    exception_controller: null
